spring:
  application:
    name: eureka-server
 
#Tomcat Embedded Server Configuration
server:  
  port: 8761
  
#Eureka Configuration Properties
eureka:
  client:
    registerWithEureka: false 
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
#  instance:
#    hostname: eureka-server
    